{% set name = "sctk" %}
{% set version = "2.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 43bd2bfe60e0ad04a563ddef025e84fca4c073f8f7c02f056b59fb8e2ec4f022
  patches:
    - 0001-fix-compiler-for-rfilter1.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - m2-base  # [win]

test:
  commands:
    - test -f $PREFIX/bin/asclite  # [not win]

about:
  home: https://github.com/usnistgov/SCTK
  summary: NIST Scoring Toolkit
  description: |
    This package contains SCTK, the NIST Scoring Toolkit. SCTK contains the
    source code, documentation and example data for the following programs:
      sclite V2.10 - "Score Lite",
      sc_stats V1.3 - sclite's Statistical Significance Comparison tool
      rover V0.1 - Recognition Output Voting Error Reduction
      asclite V1.11 - Multidimensional alignment replacement for sclite
  license: NIST-Software
  license_url: https://www.nist.gov/open/copyright-fair-use-and-licensing-statements-srd-data-software-and-technical-series-publications
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - egaznep
